# Generated by Django 4.2.5 on 2023-10-31 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/default-profile-picture.jpg', upload_to='media/profile_image/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='', max_length=600),
        ),
    ]
