# Generated by Django 4.2.5 on 2023-10-31 12:27

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_image_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/images/default-profile-picture.jpg', upload_to=user.models.img_path),
        ),
    ]
