# Generated by Django 4.2.5 on 2023-11-09 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_image'),
        ('user', '0006_comment_on_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='on_post',
        ),
        migrations.AddField(
            model_name='comment',
            name='on_post',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
            preserve_default=False,
        ),
    ]
