# Generated by Django 4.2.5 on 2023-11-09 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_remove_comment_on_post_comment_on_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='on_post',
            new_name='post',
        ),
    ]
