# Generated by Django 4.2.5 on 2023-11-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default="static/images/temp-post.png",
                upload_to="media/featured_image/%Y/%m/%d/",
            ),
        ),
    ]
