# Generated by Django 4.2.5 on 2024-02-03 10:43

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_tagstopost_tag_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=blog.models.TitleCharField(max_length=30, unique=True),
        ),
    ]
